### ISSUE TITLE
OutOfScopeException exception when method interceptor is reaching SecurityContext via Provider<SecurityContext>

### ISSUE THREAD

**Issue by Bjaku** [xvik/dropwizard-guicey#102]
**Dependencies:**
Dropwizard: 1.3.12
dropwizard-guicey:4.2.0

**Overview:**
We wanted to have a method interceptor which will be invoked before invoking JAX-RS method.

**A little introduction to code:**

In Dropwizard's initialize method we are adding AuthModule where our interceptor will be introduced:
```
    @Override
    public void initialize(Bootstrap<Configuration> bootstrap) {
        String[] packagesArray = getScannedPackages();

        bootstrap.addBundle(GuiceBundle.builder()
                .enableAutoConfig(packagesArray)
                .modules(new AuthModule())
                .build());
    }
```
AuthModule:
```
public class AuthModule extends AbstractModule {
    @Override
    protected void configure() {
        AuthorizationAfterFilterInterceptor interceptor = new AuthorizationAfterFilterInterceptor();
        requestInjection(interceptor);
        bindInterceptor(any(), annotatedWith(MethodInterceptedAuthorization.class), interceptor);
    }
```
AuthorizationAfterFilterInterceptor:
```
@Singleton
public class AuthorizationAfterFilterInterceptor implements MethodInterceptor {
    @Inject
    private Provider<SecurityContext> securityContextProvider;
    @Inject
    private Provider<ResourceInfo> resourceInfoProvider;
    @Inject
    private Injector injector;

    @Override
    public Object invoke(MethodInvocation invocation) throws Throwable {
        boolean result = authorize(invocation);
        ...
    }

    private boolean authorize(MethodInvocation invocation) {
        SecurityContext securityContext = securityContextProvider.get();
        ...
        RolesAllowed rolesAllowed = findRolesAllowed(resourceInfoProvider.get());
        ...
    }
```
And finally resource interface:
```
@PermitAll
@Path(RestConstants.EXAMPLE_PATH)
public interface ExampleResource {
    @RolesAllowed(Roles.VIEWER_ROLE)
    @GET
    @Path("/{id}")
    @Produces({ZIP_MIME_TYPE, MediaType.APPLICATION_JSON})
    Response download(@PathParam("id") @Min(1) Long id);
}
```
And resource implementation:
```
    @Override
    @MethodInterceptedAuthorization(authorizer = SomeAuthorizer.class)
    public Response download(Long id) {
        ...
    }
```
**My problem is following:**
Very very rare we are getting an error:
```com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) Error in custom provider, com.google.inject.OutOfScopeException: Cannot access scoped [javax.ws.rs.core.SecurityContext]. Either we are not currently inside an HTTP Servlet request, or you may have forgotten to apply com.google.inject.servlet.GuiceFilter as a servlet filter for this request.
  at ru.vyarus.dropwizard.guice.module.installer.util.JerseyBinding.bindJerseyComponent(JerseyBinding.java:190) (via modules: ru.vyarus.dropwizard.guice.module.GuiceBootstrapModule -> ru.vyarus.dropwizard.guice.module.jersey.Jersey2Module -> ru.vyarus.dropwizard.guice.module.jersey.hk2.GuiceBindingsModule)
  while locating javax.ws.rs.core.SecurityContext
1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at com.engine.security.interceptor.AuthorizationAfterFilterInterceptor.authorize(AuthorizationAfterFilterInterceptor.java:45)
	at com.engine.security.interceptor.AuthorizationAfterFilterInterceptor.invoke(AuthorizationAfterFilterInterceptor.java:37)
	at sun.reflect.GeneratedMethodAccessor334.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
	at io.dropwizard.jetty.ContextRoutingHandler.handle(ContextRoutingHandler.java:38)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:614)
	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handleAsync(Server.java:550)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:394)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```
SecurityContext and ResourceInfo are provided by Jersey, so if I want to have them provided by Guice I need to use Provider<> which will reach them when those will be ready. I think that my interceptor can be invoked only before JAX-RS method so context should be already present for Guice.

Could you take a look at this issue with OutOfScope exception?

Thanks,
Kuba

**Comment by xvik** [comment]
>  SecurityContext and ResourceInfo are provided by Jersey, so if I want to have them provided by Guice I need to use Provider<> which will reach them when those will be ready. I think that my interceptor can be invoked only before JAX-RS method so context should be already present for Guice.

There is a `GuiceFilter` applied above the main context (and admin too). All incoming requests are intercepted first by it so guice could bind its request scope to **request processing thread**. The weak moment here is if jersey would decide to process rest method *In a different thread*, guice would not be able to recognize request scope there (because it was assigned to request processing thread).

Normally, you should see `GuiceFilter` in stacktrace (and other possible filters).

I have seen such cases with async rest when obviously request handling thread changes. 

And by your trace, I suppose it is exactly your case:

```
at org.eclipse.jetty.server.Server.handleAsync(Server.java:550)
```

To fix this you will need to [delegate guice scope into target thread](http://xvik.github.io/dropwizard-guicey/5.0.1/guide/guice/scopes/#request-scope-transition) (example from 5.0 docs, but it's the same for 4.2 .. this example is not correct in 4.2 documentation)

100% workaround would be replacing `Provider` to direct hk2 lookup:

```java
injector.getInstance(ServiceLocator.class).getService(SecurityContext.class)
```

This way it would not rely on guice request scope and should work in your case (according to trace, jersey correctly detect its request scope).

Please tell me if you will have more info on this case: I have doubts that you use async intentionally (it should always fail in this case and not time-to-time) and if so it would be great to understand how this case appears (which is hard without the ability to reproduce it).

**Comment by xvik** [comment]
Closing as stale. Please reopen with additional info if it's still actual.
