### ISSUE TITLE
ArrayIndexOutOfBound exception when using GuiceyAppRule

### ISSUE THREAD

**Issue by usulkies** [xvik/dropwizard-guicey#103]
Hi, we have some tests using the GuiceyAppRule.
We encountered this exception which happens some times.
Stacktrace:
```
java.lang.IllegalStateException: Failed to start test environment
	at ru.vyarus.dropwizard.guice.test.GuiceyAppRule.startIfRequired(GuiceyAppRule.java:116)
	at ru.vyarus.dropwizard.guice.test.GuiceyAppRule.before(GuiceyAppRule.java:84)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 73
	at java.util.ArrayList.add(ArrayList.java:463)
	at ru.vyarus.dropwizard.guice.module.context.stat.GuiceStatsTracker$LogsInterceptor.publish(GuiceStatsTracker.java:69)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.fine(Logger.java:1516)
	at com.google.inject.internal.util.Stopwatch.resetAndLog(Stopwatch.java:43)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:136)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at ru.vyarus.dropwizard.guice.injector.DefaultInjectorFactory.createInjector(DefaultInjectorFactory.java:20)
	at ru.vyarus.dropwizard.guice.module.GuiceyRunner.createInjector(GuiceyRunner.java:109)
	at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:140)
	at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:101)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
	at ru.vyarus.dropwizard.guice.test.GuiceyAppRule$1.run(GuiceyAppRule.java:107)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at ru.vyarus.dropwizard.guice.test.GuiceyAppRule.startCommand(GuiceyAppRule.java:129)
	at ru.vyarus.dropwizard.guice.test.GuiceyAppRule.startIfRequired(GuiceyAppRule.java:113)
	... 16 more
```

**Comment by xvik** [comment]
Hi! 
I suppose you use parallel tests because it should be the only reason for this issue.

Guicey modifies j.u.l logger at startup to intercept internal guice performance logs (and be able to show them in report). The registered custom handler is not multi-threaded (in concurrent case there should be multiple handlers for a short period of time (~400ms) and they would receive logs from multiple threads).

I will fix this ofc, but for now, there is no workaround except not using parallel tests.

**Comment by usulkies** [comment]
Yes, we use parallel tests.
Thanks for your response!
