### ISSUE TITLE
Occasionally hitting ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by oeddyo** [xvik/dropwizard-guicey#105]
when running in parallel:

```
junit.jupiter.execution.parallel.enabled = true
junit.jupiter.execution.parallel.mode.default = same_thread
junit.jupiter.execution.parallel.mode.classes.default = concurrent

junit.jupiter.execution.parallel.config.dynamic.factor = 3
```

This doesn't happen often but once in a while. 

`

java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 10

	at java.base/java.util.ArrayList.add(ArrayList.java:486)
	at java.base/java.util.ArrayList.add(ArrayList.java:498)
	at ru.vyarus.dropwizard.guice.module.context.stat.GuiceStatsTracker$LogsInterceptor.publish(GuiceStatsTracker.java:69)
	at java.logging/java.util.logging.Logger.log(Logger.java:979)
	at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
	at java.logging/java.util.logging.Logger.log(Logger.java:1029)
	at java.logging/java.util.logging.Logger.fine(Logger.java:1828)
	at com.google.inject.internal.util.Stopwatch.resetAndLog(Stopwatch.java:43)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:187)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at ru.vyarus.dropwizard.guice.injector.DefaultInjectorFactory.createInjector(DefaultInjectorFactory.java:20)
	at ru.vyarus.dropwizard.guice.module.GuiceyRunner.createInjector(GuiceyRunner.java:109)
	at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:140)
	at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:101)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:183)
	at io.dropwizard.testing.DropwizardTestSupport$2.run(DropwizardTestSupport.java:294)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.testing.DropwizardTestSupport.startIfRequired(DropwizardTestSupport.java:330)
	at io.dropwizard.testing.DropwizardTestSupport.before(DropwizardTestSupport.java:223)
	at io.dropwizard.testing.junit5.DropwizardAppExtension.before(DropwizardAppExtension.java:181)
	at com.kalasearch.restful.integration.IntegrationExtension.beforeAll(IntegrationExtension.java:67)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

`

**Comment by xvik** [comment]
Ah, yes, it's a known issue #103. Already fixed in trunk.
There is no workaround for the current version, except not using parallel tests, sorry.

I can only suggest [using snapshot](https://github.com/xvik/dropwizard-guicey#snapshots) for now

**Comment by oeddyo** [comment]
No rush on this. Thanks @xvik
