### ISSUE TITLE
NoClassDefFoundError ValueFactoryProvider - Missing dependency?

### ISSUE THREAD

**Issue by chriskessel** [xvik/dropwizard-guicey#132]
I'm moving to dropwizard-guicey from dropwizard-guice as well as upgrading from Dropwizard 1 > Dropwizard 2.

I'm getting this error on startup. Am I missing a dependency?

```
java.lang.NoClassDefFoundError: org/glassfish/jersey/server/spi/internal/ValueFactoryProvider
	at ru.vyarus.dropwizard.guice.module.installer.feature.jersey.provider.JerseyProviderInstaller.<clinit>(JerseyProviderInstaller.java:48)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346)
	at java.base/java.lang.Class.newInstance(Class.java:604)
	at ru.vyarus.dropwizard.guice.module.installer.InstallerModule.prepareInstallers(InstallerModule.java:111)
	at ru.vyarus.dropwizard.guice.module.installer.InstallerModule.configure(InstallerModule.java:61)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
	at com.google.inject.AbstractModule.install(AbstractModule.java:103)
	at ru.vyarus.dropwizard.guice.module.GuiceSupportModule.configure(GuiceSupportModule.java:79)
```

**Comment by xvik** [comment]
Dropwizard 2 depends on *very much* changed jersey. 
`ValueFactoryProvider` was removed, use `ValueParamProvider` instead.

There was a migration guide in [guicey 5.0.0 docs](http://xvik.github.io/dropwizard-guicey/5.0.0/about/release-notes/#migration-guide) (see classes substitution matrix for changed jersey classes).

Also, please check that you're using guicey 5.0.0 or 5.1.0 because only these versions are compatible with dropwizard 2 (and it looks like the version in your project is different according to your stacktrace).

**Comment by chriskessel** [comment]
Ah, oops. I had 4.1 dropwizard-guicey. Not sure why...must have fat fingered the version number :(
