### ISSUE TITLE
[Improvement] Lambda module throws `Failed to analyze guice bindings` exception

### ISSUE THREAD

**Issue by cielowu** [xvik/dropwizard-guicey#160]
When you used an anonymous module such as directly using lambda to create a module, `dropwizard-guicey` will fail on analyze guice bindings.

This is not an issue, but the exception looks like it will fail the analysis process.

Maybe a warning message with a default name is better? Instead of directly throw exception.

```
ERROR [2021-04-04 02:32:37,028] ru.vyarus.dropwizard.guice.module.installer.internal.ModulesSupport: Failed to analyze guice bindings - skipping this step. Note that configuration from bindings may be switched off with GuiceyOptions.AnalyzeGuiceModules option.
! java.lang.ClassNotFoundException: com.example.helloworld.HelloWorldApplication$$Lambda$73/0x0000000800c0d440
! at java.base/java.lang.Class.forName0(Native Method)
! at java.base/java.lang.Class.forName(Class.java:333)
! at ru.vyarus.dropwizard.guice.module.installer.util.BindingUtils.getModuleClass(BindingUtils.java:64)
! ... 14 common frames omitted
! Causing: java.lang.IllegalStateException: Failed to resolve module class
! at ru.vyarus.dropwizard.guice.module.installer.util.BindingUtils.getModuleClass(BindingUtils.java:66)
! at ru.vyarus.dropwizard.guice.module.installer.util.BindingUtils.getTopDeclarationModule(BindingUtils.java:84)
! at ru.vyarus.dropwizard.guice.module.installer.internal.ModulesSupport.checkBindingRemoveRequired(ModulesSupport.java:195)
! at ru.vyarus.dropwizard.guice.module.installer.internal.ModulesSupport.analyzeAndFilterBindings(ModulesSupport.java:165)
! at ru.vyarus.dropwizard.guice.module.installer.internal.ModulesSupport.analyzeModules(ModulesSupport.java:118)
! at ru.vyarus.dropwizard.guice.module.installer.internal.ModulesSupport.prepareModules(ModulesSupport.java:81)
! at ru.vyarus.dropwizard.guice.module.GuiceyRunner.analyzeAndRepackageBindings(GuiceyRunner.java:89)
! at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:141)
! at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:101)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:58)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at com.example.helloworld.HelloWorldApplication.main(HelloWorldApplication.java:11)
```

**Comment by xvik** [comment]
The workaround is to disable [modules analysis](http://xvik.github.io/dropwizard-guicey/5.3.0/guide/guice/module-analysis/):

```java
GuiceBundle.builder()
   ...
   .option(GuiceyOptions.AnalyzeModules, false)
   .build()
```

Without analysis, you will mainly lose the ability to declare extensions directly in modules, but usually, it's not much used.

I will look at this, but could you please post an example of a module declaration causing the exception to simplify reproduction?

**Comment by cielowu** [comment]
Here's a simple example I used to reproduce the issue:

```
  @Override
  public void initialize(Bootstrap<Configuration> bootstrap) {
    bootstrap.addBundle(GuiceBundle.builder()
        .enableAutoConfig(getClass().getPackage().getName())
        .modules(binder -> binder.bind(String.class).annotatedWith(DefaultName.class).toInstance("John"))
        .build());
  }
```

Yes, it is easy to work around by disabling the option, that's why it's not a major issue.
