### ISSUE TITLE
Cannot work with JDK 16?

### ISSUE THREAD

**Issue by xiao-pp** [xvik/dropwizard-guicey#178]
Everything works fine with JDK 14. Today I tried to bump my project to JDK 16 and got:
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @270421f5
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:159)
	at javassist.util.proxy.DefineClassHelper$JavaOther.defineClass(DefineClassHelper.java:213)
	at javassist.util.proxy.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:52)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
	at javassist.ClassPool.toClass(ClassPool.java:1240)
	at javassist.CtClass.toClass(CtClass.java:1392)
	at ru.vyarus.guice.ext.core.generator.DynamicClassGenerator.generateClass(DynamicClassGenerator.java:140)
	... 45 more
```

Dropwizard `2.0.24`
Guicey `5.3.0-1`
Guice `5.0.1`

**Comment by xvik** [comment]
Oh, seems to be [this issue](https://github.com/jboss-javassist/javassist/issues/369). 
The problem is actually related to [guice-ext-annotations](https://github.com/xvik/guice-ext-annotations). 

As I can see there is no workaround. I will try to fix guice-ext-annotations (hopefully soon).

**Comment by xvik** [comment]
Fixed guice-ext-annotations [released](https://github.com/xvik/guice-ext-annotations/releases/tag/1.4.0). You'll need to update the version manually (to override transient dep):

```
implementation 'ru.vyarus:guice-ext-annotations:1.4.0'
```

Most likely, jdbi will work now (haven't checked it yet, but the original issue is fixed).

Another workaround is adding jvm flag:

```
--illegal-access=permit
```

Jdk 16 changed the default to deny (this flag would be removed in jdk 17)
