### ISSUE TITLE
ExceptionMapper manual registration fails without @Provides annotation

### ISSUE THREAD

**Issue by okravets-intellias** [xvik/dropwizard-guicey#265]
With vanilla DropWizard javax.ws.rs.ext.Provider annotation is not required on ExceptionMapper.
```java
environment.jersey().register(MyExceptionMapper.class); // works fine
```
But with Guicey I do
```java
GuiceBundle.builder()
....
.extensions(MyExceptionMapper.class)
```
and here's what happens:
```
Exception in thread "main" java.lang.IllegalStateException: No installer found for extension com.example.exceptions.MyExceptionMapper. Available installers: lifecycle, managed, jerseyfeature, jerseyprovider, resource, eagersingleton, healthcheck, task, plugin, webservlet, webfilter, weblistener
	at ru.vyarus.dropwizard.guice.module.GuiceyInitializer.resolveExtensions(GuiceyInitializer.java:138)
	at ru.vyarus.dropwizard.guice.GuiceBundle.initialize(GuiceBundle.java:125)
	at io.dropwizard.setup.Bootstrap.addBundle(Bootstrap.java:150)
	at com.example.Main.initialize(Main.java:60)
	at io.dropwizard.Application.run(Application.java:88)
	at com.example.Main.main(Main.java:49)
```
I suspect that will also happen with any other supported component without javax.ws.rs.ext.Provider annotation.
In case of manual registration I would expect behavior that is consistent with vanilla DW.

Perhaps changing JerseyProviderInstaller#matches as below would do the trick?

```java
@Override
    public boolean matches(final Class<?> type) {
        return FeatureUtils.hasAnnotation(type, Provider.class) || EXTENSION_TYPES.contains(type);
    }
```

**Comment by xvik** [comment]
Agree, will update it (but will read docs first to be sure).
