### ISSUE TITLE
Support Dropwizard 5.0

### ISSUE THREAD

**Issue by lifey** [xvik/dropwizard-guicey#376]
Dropwizard 5.0 (bundling Jetty12) is in alpha release. https://central.sonatype.com/artifact/io.dropwizard/dropwizard-core/overview
Currently dropwizard-guicey does not support it and fails to start 
java.lang.NoSuchMethodError: 'void io.dropwizard.jetty.MutableServletContextHandler.setAttribute(java.lang.String, java.lang.Object)'
	at ru.vyarus.dropwizard.guice.module.context.SharedConfigurationState.listen(SharedConfigurationState.java:258)
	at ru.vyarus.dropwizard.guice.module.context.ConfigurationContext.runPhaseStarted(ConfigurationContext.java:710)
	at ru.vyarus.dropwizard.guice.module.GuiceyRunner.<init>(GuiceyRunner.java:43)
	at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:133)
	at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:101)
	at io.dropwizard.core.setup.Bootstrap.run(Bootstrap.java:199)

I have tried to compile it and there are several compilation issues relate to jakarta-ee decoupling from jetty

**Comment by lifey** [comment]
Thanks @xvik if you need help with this LMK :)

**Comment by xvik** [comment]
Checked: everything is good. Just a few packages renamed (for example, `org.eclipse.jetty.servlet.FilterHolder` become `org.eclipse.jetty.ee10.servlet.FilterHolder`).

Plus, `ServerPushFilterFactory` was removed with related configuration (it was already deprecated).

There is a problem with admin-rest extension in case of async resources, but I doubt anyone use async admin rest at all.
Will look closer later.

I did not push the changes (just stashed) because I don't want to maintain another branch right now.
Will push it into master when at least beta would be released.

**Comment by lifey** [comment]
Thanks @xvik for the rapid response

**Comment by xvik** [comment]
Dropwizard 5 support (alpha 2) [pushed into master](https://github.com/xvik/dropwizard-guicey/commit/586f66e478b05af0a7c16b666e0535e63c0c44c0)

**Comment by xvik** [comment]
Actual SNAPSHOT version (for dropwizard 5) is published now as [github package](https://github.com/xvik?tab=packages&repo_name=dropwizard-guicey)

WARN: github packages require authentiacation token for access (no unauthorized access). Read [snapshots usage doc](https://github.com/xvik/dropwizard-guicey?tab=readme-ov-file#snapshots) (click on triangle to open section) for installation instructions.
At least, something (rather than nothing at all).

Snapshot published only when all tests pass (so should be no totally broken snapshots). 
Don't pay attention for [red CI](https://github.com/xvik/dropwizard-guicey/actions/workflows/CI.yml): I'm trying to run examples with actual snapshot on each commit (but it doesn't work yet).

**Comment by kurtseebauer** [comment]
dropwizard released a RC version for 5.0, so a release candidate on maven central would be helpful for testing. 
https://github.com/dropwizard/dropwizard/releases/tag/v5.0.0-rc.1
thx! :-)

**Comment by xvik** [comment]
For now, I can suggest to use the [github package](https://github.com/xvik/dropwizard-guicey?tab=readme-ov-file#snapshots). Not very comfortable, I understand, but it's not hard to configure.
Maybe will release rc later, but can't promise (currently busy with other release)

**Comment by xvik** [comment]
For simplicity, [described required configuration in details](https://blog.vyarus.ru/using-github-packages-in-gradle-and-maven-projects)

After token creation just add new repository. Token could be put directly inside build file (not a problem for local checks)

```groovy
repositories {
    mavenCentral()
    maven {
        url  = 'https://maven.pkg.github.com/xvik/dropwizard-guicey'
        credentials {
            username = 'my user name'
            password = 'github token'
        }
    }
}
```

**Comment by xvik** [comment]
Published [8.0.0-rc.1](https://github.com/xvik/dropwizard-guicey/releases/tag/8.0.0-rc.1) for dropwizard 5-rc1.
There are no major changes (see changelog). Includes some minor changes not yet published for 7.x, but soon would be.

**Comment by xvik** [comment]
I know that rc2 is published. 
I almost finished with the new features (would be a large update), but haven't updated the documentation yet.

But, documentation actualization will take a lot of time, so (with the new circumstances) the plan is the following:

* I'll finish with release notes (brief description of all changes - better then nothing)
* Release rc.2 (next week)
* Finish documentation 
* Backport all changes for dropwizard 4.x and 3.x branches and release (2-3 weeks)

It is also possible to update ASM version bundled with guice, but I'm not sure it's a good idea. Please share your opinion [in the discussion](https://github.com/xvik/dropwizard-guicey/discussions/422)

**Comment by xvik** [comment]
[8.0.0-rc.2 released](https://github.com/xvik/dropwizard-guicey/releases/tag/8.0.0-rc.2) (with dropwizard 5-rc2).

See [release notes](https://xvik.github.io/dropwizard-guicey/8.0.0-rc.2/about/release-notes/) (full documentation is not ready yet)

Also, [released 7.2.0-rc.1](https://github.com/xvik/dropwizard-guicey/releases/tag/7.2.0-rc.1) (same changes backported for dropwizard 4)

**Comment by xvik** [comment]
[8.0.0-rc.3 released](https://github.com/xvik/dropwizard-guicey/releases/tag/8.0.0-rc.3) with the same changes as in [7.2.0 release](https://xvik.github.io/dropwizard-guicey/7.2.0/about/release-notes/) (7.2.0 documentation is actual for 8.0.0).

Documentation updated. [General test tools](https://xvik.github.io/dropwizard-guicey/7.2.0/guide/test/general/general/) and [junit 5](https://xvik.github.io/dropwizard-guicey/7.2.0/guide/test/junit5/setup/) sections were completely reworked.

Also, [openapi client/server generation example](https://github.com/xvik/dropwizard-guicey/tree/master/examples/openapi-client-server) added

**Comment by xvik** [comment]
Dropwizard 5 released yesterday, but guicey release will delay in a couple of weeks because I need to finish reworking test client (almost done, but need to write tests and validate api) - did not expect dw 5 release so soon.

Please, for now, use the [actual snapshot](https://central.sonatype.com/repository/maven-snapshots/ru/vyarus/dropwizard-guicey/maven-metadata.xml) (8.0.0-SNAPSHOT, already updated to released dropwizard 5) from maven central:

```groovy
repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = 'Central Portal Snapshots'
            url = 'https://central.sonatype.com/repository/maven-snapshots/'
            mavenContent {
                snapshotsOnly()
                includeGroupAndSubgroups('ru.vyarus')
            }
        }
    }

dependencies {
    implementation 'ru.vyarus:dropwizard-guicey:8.0.0-SNAPSHOT'
}
```

The snapshot is stable - it is almost the same as the latest 7.x release (just few minor changes). Upcoming client change will be backported to 7.x and 6.x as usual.
