### ISSUE TITLE
Support Jersey SSE bindings

### ISSUE THREAD

**Issue by muliyul** [xvik/dropwizard-guicey#399]
This does not work:

```kotlin
@GET
@Path("/subscribe")
@Consumes("text/event-stream")
@CacheControl(noCache = true)
fun chat(@Context sseEventSink: SseEventSink, @Context sse: Sse)
```

```
1) [Guice/ErrorInCustomProvider]: NullPointerException: Jersey InjectionManager is not yet available
  at Jersey2Module.configure(Jersey2Module.java:59)
      \_ installed by: GuiceBootstrapModule -> Jersey2Module
  at AuthFilter.injectionManager(AuthFilter.java:21)
      \_ for field injectionManager
  at AbstractJerseyInstaller.bindInGuice(AbstractJerseyInstaller.java:68)
      \_ installed by: GuiceBootstrapModule -> InstallerModule
  while locating AuthFeature
```

**Comment by muliyul** [comment]
Actually it was my bad, I had my `AuthFeature` extend `ChainedAuthFilter` instead of `AuthDynamicFeature`.
