### ISSUE TITLE
Configuration bindings prints value but at runtime throws NullPointerException

### ISSUE THREAD

**Issue by thiagohora** [xvik/dropwizard-guicey#409]
NullPointerException when @Inject a particular configuration property 

```
ru.vyarus.dropwizard.guice.debug.YamlBindingsDiagnostic: Available configuration bindings = 
...

Unique sub configuration objects bindings:

  MyConfig.batchOperations
            @Config BatchOperationsConfig = BatchOperationsConfig(datasets=DatasetsConfig[test=2])
```

```
    @Inject
    public MyService(@Config @NonNull BatchOperationsConfig batchOperationsConfig) {
       ...
```

**Comment by xvik** [comment]
Could you please prepare an example project?

I tried to reproduce this, but it works. There must be some important specific in your project, not mentioned here.
I can't imagine what could it be (and so I need some sample project to reproduce and investigate this problem).

The same configuration introspection data is used for configuration report and for actual bindings, so if report shows something - it should be bound in context. Also, as it shows value in report, the same value must be bound - have no idea how null could be bound instead (and we could be sure that binding exists because otherwise guice would complain).

You could also try to enable guice report:
```java
.printAllGuiceBindings()
```

which shows all actual guice bindings (whreas configurtation report shows bindings that should be registered). It does not show the binding value (probably good idea for a new report), but you'll see if `@Config BatchOperationsConfig` binding is available at all.
Not sure if it will show anything new because we already know the binding exists (maybe it will push you into right direction)

**Comment by thiagohora** [comment]
```
ERROR [2024-11-08 14:28:15,408] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 997baca962f05149
2024-11-08T14:28:15.421524719Z ! java.lang.NullPointerException: Cannot invoke "com.my.project.infrastructure.BatchOperationsConfig$DatasetsConfig.getMaxExperimentInClauseSize()" because the return value of "com.my.project.infrastructure.BatchOperationsConfig.getDatasets()" is null
2024-11-08T14:28:15.421528428Z ! at com.my.project.domain.DatasetServiceImpl.lambda$find$11(DatasetService.java:271)
2024-11-08T14:28:15.421529928Z ! at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
2024-11-08T14:28:15.421531053Z ! at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
2024-11-08T14:28:15.421544844Z ! at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
2024-11-08T14:28:15.421545886Z ! at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
2024-11-08T14:28:15.421546803Z ! at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
2024-11-08T14:28:15.421547761Z ! at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:850)
2024-11-08T14:28:15.421548636Z ! at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:612)
2024-11-08T14:28:15.421549594Z ! at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:592)
2024-11-08T14:28:15.421550511Z ! at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:469)
2024-11-08T14:28:15.421551428Z ! at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:261)
2024-11-08T14:28:15.421552344Z ! at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
2024-11-08T14:28:15.421553261Z ! 
```

```
─ ConfigBindingModule          (r.v.d.g.m.yaml.bind)      
2024-11-08T14:07:13.800219219Z     │       ├── instance             [@Singleton]     ConfigurationTree                               at ru.vyarus.dropwizard.guice.module.yaml.bind.ConfigBindingModule.configure(ConfigBindingModule.java:52)
2024-11-08T14:07:13.800220135Z     │       ├── instance             [@Singleton]     Configuration                                   at ru.vyarus.dropwizard.guice.module.yaml.bind.ConfigBindingModule.bindRootTypes(ConfigBindingModule.java:102)
2024-11-08T14:07:13.800221094Z     │       ├── instance             [@Singleton]     MyAPPConfiguration                               at ru.vyarus.dropwizard.guice.module.yaml.bind.ConfigBindingModule.bindRootTypes(ConfigBindingModule.java:102)
2024-11-08T14:07:13.800222010Z     │       ├── instance             [@Singleton]     @Config Configuration                           at ru.vyarus.dropwizard.guice.module.yaml.bind.ConfigBindingModule.bindRootTypes(ConfigBindingModule.java:104)
2024-11-08T14:07:13.800224010Z     │       ├── instance             [@Singleton]     @ConfigMyAPPConfiguration                       at ru.vyarus.dropwizard.guice.module.yaml.bind.ConfigBindingModule.bindRootTypes(ConfigBindingModule.java:104)
2024-11-08T14:07:13.800224927Z     │       ├── instance             [@Singleton]     @Config AdminFactory                            at ru.vyarus.dropwizard.guice.module.yaml.bind.ConfigBindingModule.bindUniqueSubConfigurations(ConfigBindingModule.java:117)
2024-11-08T14:07:13.800225844Z     │       ├── instance             [@Singleton]     @Config AuthenticationConfig                    at ru.vyarus.dropwizard.guice.module.yaml.bind.ConfigBindingModule.bindUniqueSubConfigurations(ConfigBindingModule.java:117)
2024-11-08T14:07:13.800226760Z     │       ├── instance             [@Singleton]     @Config BatchOperationsConfig                   at ru.vyarus.dropwizard.guice.module.yaml.bind.ConfigBindingModule.bindUniqueSubConfigurations(ConfigBindingModule.java:117)
2024-11-08T14:07:13.800227635Z     │       ├── instance             [@Singleton]     @Config CorsConfig                  
```

**Comment by xvik** [comment]
Sorry, I can't reproduce this. There must be some side effect: either `DatasetServiceImpl.batchOperationsConfig` instance is different from `MyAPPConfiguration.batchOperations` or somewhere `BatchOperationsConfig.setDatasets(null)` is called.

One way to verify is by injecting `MyAPPConfiguration` in constructor to be able to compare instances:

```java
@Singleton
@RequiredArgsConstructor(onConstructor_ = @Inject)
@Slf4j
class DatasetServiceImpl implements DatasetService {

    private static final String DATASET_ALREADY_EXISTS = "Dataset already exists";

    private final @NonNull IdGenerator idGenerator;
    private final @NonNull TransactionTemplate template;
    private final @NonNull Provider<RequestContext> requestContext;
    private final @NonNull EntitytDAO entityDAO;
    private final @NonNull @Config BatchOperationsConfig batchOperationsConfig;
    private final @NonNull MyAPPConfiguration configuration;

    @Override
    public DatasetPage find(int page, int size, @NonNull DatasetCriteria criteria) {
        String workspaceId = requestContext.get().getWorkspaceId();
        String userName = requestContext.get().getUserName();

        // must be the same instance
         System.out.println(System.idenityHashCode(configuration.getBatchOperationsConfig()))
         System.out.println(System.idenityHashCode(batchOperationsConfig))

        // must both be null
        System.out.println(configuration.getBatchOperationsConfig().getDatasets())
        System.out.println(batchOperationsConfig().getDatasets())

        int maxExperimentInClauseSize = batchOperationsConfig.getDatasets().getMaxExperimentInClauseSize();
        //...
     } 
```

If you'll make sure that `BatchOperationsConfig` is the same object then something sets null into datasets: try to debug getter (or println inside getter to track interactions)

Or, to avoid sharing project in public, you can send it directly to my email vyarus[at]gmail.com and I'll investigate the probelm.

**Comment by thiagohora** [comment]
I just tested yesterday, it seems somehow related to docker. Out of the
container it works, or the JVM, in docker I'm using correto 21 2033

**Comment by xvik** [comment]
I run all tests with correto 21 and everything works (it would be very strange if it didn't).

I assume that the simplest explanation could be server configuration file (yaml). 
If `BatchOperationsConfig` did not initialize `DatasetsConfig` and there is no configuration for it in yaml file, then it would remain null.
But, in this case,  configuration report should also show null values.

No other ideas. Only debug on real case could help.

**Comment by thiagohora** [comment]
I will try to create a public repo with this issue reproduced

**Comment by xvik** [comment]
> guice seems no to see the annotation

I doubt. It's more likely annotation is not passed.

I tried to play with lombok and I have no problems (even don't need to configure lombok.copyableAnnotations, which is starnge). My lombok version is 1.18.32.

You can check if annotation is actually copied with ProvisionListener:

```java
 // GuiceBundle.builder()

       .modules(binder -> binder.bindListener(
               // apply only for BatchOperationsConfig provision
               binding -> binding.getKey().getTypeLiteral().getRawType().isAssignableFrom(BatchOperationsConfig.class),

                new ProvisionListener() {
                       @Override
                       public <T> void onProvision(ProvisionInvocation<T> provision) {
                             System.out.println(">>>> " + provision.getBinding().getKey().toString());
                       }
        }))
```

This listener will react on BatchOperationsConfig injection, and, if its requested without annotation, you'll see something like this (I was testing on DataSourceFactory):

```
>>>> Key[type=io.dropwizard.db.DataSourceFactory, annotation=[none]]
```

Normally (when annotation is copied), you should see:

```
>>>> Key[type=io.dropwizard.db.DataSourceFactory, annotation=@ru.vyarus.dropwizard.guice.module.yaml.bind.Config(value=)]
```

If you'll see that binding without annotation is requested then lombok didn't actually copied the annotation. 
In this case, gucie consider this as jit-in-time binding and constructs new BatchOperationsConfig instance.

Should be a lombok issue.

**Comment by xvik** [comment]
Not sure if it would help, but in just released 7.2.0 there is a [provision report](https://xvik.github.io/dropwizard-guicey/latest/guide/diagnostic/guice-provision-report/) (`.printGuiceProvisionTime()`) which also detects accidental JIT injections (unqualified injection when qualified bindings declared):

```
    Possible mistakes (unqualified JIT bindings):

         @Inject Sub:
              instance             [@Singleton]     @Config("val2") Sub                                                                   : 0.0005 ms        ru.vyarus.dropwizard.guice.module.yaml.bind.ConfigBindingModule.bindValuePaths(ConfigBindingModule.java:129)
              instance             [@Singleton]     @Marker Sub                                                                           : 0.0007 ms        ru.vyarus.dropwizard.guice.module.yaml.bind.ConfigBindingModule.bindCustomQualifiers(ConfigBindingModule.java:87)
            > JIT                  [@Prototype]     Sub                
```

If `@Config` annotation is not copied, it should show it as a JIT injection.

**Comment by thiagohora** [comment]
I will try it out
