### ISSUE TITLE
NullPointerException: Jersey InjectionManager is not yet available

### ISSUE THREAD

**Issue by paddy-axio** [xvik/dropwizard-guicey#412]
I upgraded Dropwizard to 4.x. What seemed to work until v3.0.3 doesn't work anymore (even after following the migration guide and I use ru.vyarus.guicey:guicey-bom:7.1.4). 

If I understand correctly, the not-yet-initialized `injectionManager` seems to be expected eagerly during `injectDynamically()` in `com.google.inject.internal.InternalInjectorCreator#build`

I doubt it has to do with `enableAutoConfig(getClass().getPackage().getName())`
Am I missing something?

Here is my code
```
 @Override
    public void initialize(final Bootstrap<MyConfiguration> bootstrap) {
        bootstrap.getObjectMapper().disable(DeserializationFeature.ACCEPT_FLOAT_AS_INT);
        bootstrap.getObjectMapper().enable(FAIL_ON_UNKNOWN_PROPERTIES);

        bootstrap.addBundle(GuiceBundle.builder()
            .enableAutoConfig(getClass().getPackage().getName())
            .modules(new MyModule())
            .extensions(AuthorizationFilter.class)
            .build());
...
```
and the logs

```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInCustomProvider]: NullPointerException: Jersey InjectionManager is not yet available
  at Jersey2Module.configure(Jersey2Module.java:59)
      \_ installed by: GuiceBootstrapModule -> Jersey2Module
  at AuthFilter.injectionManager(AuthFilter.java:21)
      \_ for field injectionManager
  at AbstractJerseyInstaller.bindInGuice(AbstractJerseyInstaller.java:68)
      \_ installed by: GuiceBootstrapModule -> InstallerModule
  while locating CertificateAuthFilter

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
AbstractJerseyInstaller: "ru.vyarus.dropwizard.guice.module.installer.feature.jersey.AbstractJerseyInstaller"
AuthFilter:              "io.dropwizard.auth.AuthFilter"
CertificateAuthFilter:   "com.example.authentication.CertificateAuthFilter"
GuiceBootstrapModule:    "ru.vyarus.dropwizard.guice.module.GuiceBootstrapModule"
InstallerModule:         "ru.vyarus.dropwizard.guice.module.installer.InstallerModule"
Jersey2Module:           "ru.vyarus.dropwizard.guice.module.jersey.Jersey2Module"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:190)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at ru.vyarus.dropwizard.guice.injector.DefaultInjectorFactory.createInjector(DefaultInjectorFactory.java:20)
	at ru.vyarus.dropwizard.guice.module.GuiceyRunner.createInjector(GuiceyRunner.java:109)
	at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:140)
	at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:101)
	at io.dropwizard.core.setup.Bootstrap.run(Bootstrap.java:199)
	at io.dropwizard.core.cli.EnvironmentCommand.run(EnvironmentCommand.java:65)
	at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.core.cli.Cli.run(Cli.java:78)
	at io.dropwizard.core.Application.run(Application.java:94)
	at com.example.App.main(App.java:45)
Caused by: java.lang.NullPointerException: Jersey InjectionManager is not yet available
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:922)
	at ru.vyarus.dropwizard.guice.module.jersey.GuiceFeature.get(GuiceFeature.java:90)
	at ru.vyarus.dropwizard.guice.module.jersey.GuiceFeature.get(GuiceFeature.java:51)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:57)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	... 12 more
```

**Comment by xvik** [comment]
> If I understand correctly, the not-yet-initialized injectionManager seems to be expected eagerly

exactly

> during injectDynamically() in com.google.inject.internal.InternalInjectorCreator#build

not quite


In essence, the problem caused by `io.dropwizard.auth.AuthFilter` because it directly requests `InjectionManager`:

```java
@Priority(Priorities.AUTHENTICATION)
public abstract class AuthFilter<C, P extends Principal> implements ContainerRequestFilter {
   ....
   
    @Nullable
    @Inject
    private InjectionManager injectionManager;

```

But the actual problem is in the `com.example.authentication.CertificateAuthFilter` (or around its registration) - something.  

As your CertificateAuthFilter is obviously a guice bean - it is created with guice context startup, causing too early field injection. To avoid this, auth filter must be registered with the help of `AuthDynamicFeature`

The full auth example you can [find here](https://github.com/xvik/dropwizard-guicey/blob/master/examples/integration-auth/src/main/java/ru/vyarus/dropwizard/guice/examples/auth/OAuthDynamicFeature.java)

```java
@Singleton
@Provider
class OAuthDynamicFeature extends AuthDynamicFeature {

    @Inject
    OAuthDynamicFeature(OAuthAuthenticator authenticator, OAuthAuthorizer authorizer, Environment environment) {
        super(new OAuthCredentialAuthFilter.Builder<User>()
                .setAuthenticator(authenticator)
                .setAuthorizer(authorizer)
                .setPrefix("Bearer")
                .buildAuthFilter())

                ...
    }
```

`OAuthAuthenticator` and `OAuthAuthorizer` are gucie beans and OAuthDynamicFeature would be a guice bean (it is a `Feature` extension, installed by JerseyProviderInstaller).
But `AuthFilter` is not a guice bean:`super(new OAuthCredentialAuthFilter.Builder<User>()` which resolves problem with injection manager (it would be properly initialized, but when web context starts).

> I upgraded Dropwizard to 4.x. What seemed to work until v3.0.3 doesn't work anymore

That is strange: dropwizard 3 and 4 are nearly the same (with only javax - jakarta package difference). I checked AuthFilter implementation is the same for both versions. It shouldn't be working before too.

**Comment by paddy-axio** [comment]
Thanks for the detailed response.

Is it correct to say classes that extend `AuthFilter` can't exist within the packages that are auto-configured?

```
import io.dropwizard.auth.AuthFilter;

@Priority(Priorities.AUTHENTICATION)
public class CertificateAuthFilter extends AuthFilter {
   ...
}
```

**Comment by xvik** [comment]
Hmm, indeed, autoscan will detect it. 
As a workaround, you can annotate such filter with `@InvisibleForScanner` and classpath scanner would ignore it
