### ISSUE TITLE
jdbi2 Hikari PooledDataSource error

### ISSUE THREAD

**Issue by pipinet** [xvik/dropwizard-guicey#51]
**error info:**
```
INFO  [2018-06-21 16:47:29,848] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...
INFO  [2018-06-21 16:47:29,935] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Start completed.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Could not find a suitable constructor in bw.wap.db.HikariManagedPooledDataSource. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at bw.wap.db.HikariManagedPooledDataSource.class(HikariManagedPooledDataSource.java:13)
  at ru.vyarus.dropwizard.guice.module.installer.InstallerModule.bindExtension(InstallerModule.java:191) (via modules: ru.vyarus.dropwizard.guice.module.GuiceSupportModule -> ru.vyarus.dropwizard.guice.module.installer.InstallerModule)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at ru.vyarus.dropwizard.guice.injector.DefaultInjectorFactory.createInjector(DefaultInjectorFactory.java:20)
        at ru.vyarus.dropwizard.guice.GuiceBundle.createInjector(GuiceBundle.java:191)
        at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:138)
        at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:93)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at bw.wap.App.main(App.java:17)


FAILURE: Build failed with an exception.
```

1. when i use DataSourceFactory, not remove HikariManagedPooledDataSource class. not work.
2. when i use DataSourceFactory, remove HikariManagedPooledDataSource class. work!!!

so , i think auto scan will auto inject  HikariManagedPooledDataSource class. but i will new instance by myself.

rep:https://github.com/bwlibs/guicey-error

**Comment by xvik** [comment]
Hi! Thank you very much for the repo! 

You are right: `HikariManagedPooledDataSource` is a `Managed` object and it is inside application package configured for classpath scan. So guicey recognize `HikariManagedPooledDataSource` as Managed and tries to install it as managed extension, which is impossible (due to constructor).

You need to exclude it from classpath scan:
* Either move this class into package not visible for scanner (or configure classpath scan only to some sub packages instead of entire application package)
* Or simply annotate `HikariManagedPooledDataSource` with `@InvisibleForScanner` and it will be ignored

**Comment by pipinet** [comment]
hi!   Thank you very much for the solution you offered.
