### ISSUE TITLE
Configuration processing fails in ConfigTreeBuilder.build(bootstrap, configuration)

### ISSUE THREAD

**Issue by krutsko** [xvik/dropwizard-guicey#53]
Hello 

After upgrade to 4.2.0 encountered exception during initialization of GuiceBundle. 
What is the the purpose of such exercise, "Analyze configuration object to extract bindable parts" ?
Seems, we don't need, can we make this step optional? 

```
2018-07-13T12:24:23.012Z ERROR main "" ""       - Error during run configuration command
! java.lang.IllegalArgumentException: Failed to getValue() with method com.netflix.config.DynamicProperty#getBoolean(0 params): null
! at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.getValue(AnnotatedMethod.java:186)
! at ru.vyarus.dropwizard.guice.module.yaml.ConfigTreeBuilder.readValue(ConfigTreeBuilder.java:393)
! at ru.vyarus.dropwizard.guice.module.yaml.ConfigTreeBuilder.resolvePaths(ConfigTreeBuilder.java:147)
! at ru.vyarus.dropwizard.guice.module.yaml.ConfigTreeBuilder.resolvePaths(ConfigTreeBuilder.java:161)
! at ru.vyarus.dropwizard.guice.module.yaml.ConfigTreeBuilder.resolvePaths(ConfigTreeBuilder.java:161)
! at ru.vyarus.dropwizard.guice.module.yaml.ConfigTreeBuilder.resolvePaths(ConfigTreeBuilder.java:161)
! at ru.vyarus.dropwizard.guice.module.yaml.ConfigTreeBuilder.build(ConfigTreeBuilder.java:83)
! at ru.vyarus.dropwizard.guice.module.context.ConfigurationContext.runPhaseStarted(ConfigurationContext.java:509)
! at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:141)
! at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:102)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
! at command.EnvironmentCommand.run(EnvironmentCommand.java:28)
! at command.ConfiguredCommand.run(ConfiguredCommand.java:56)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:93)
! at hello.HelloService.main(HelloService.java:18)
! Caused by: java.lang.reflect.InvocationTargetException: null
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.getValue(AnnotatedMethod.java:183)
! ... 15 common frames omitted
! Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException
! at com.netflix.config.DynamicProperty$CachedValue.getValue(DynamicProperty.java:121)
! at com.netflix.config.DynamicProperty.getBoolean(DynamicProperty.java:327)
! ... 20 common frames omitted
! Caused by: java.lang.IllegalArgumentException: null
! at com.netflix.config.DynamicProperty$1.parse(DynamicProperty.java:190)
! at com.netflix.config.DynamicProperty$1.parse(DynamicProperty.java:178)
! at com.netflix.config.DynamicProperty$CachedValue.getValue(DynamicProperty.java:117)
! ... 21 common frames omitted
```

**Comment by xvik** [comment]
Hi!

Can you please show your configuration class so I could reproduce this? Or at least describe how netflix config is used inside.

This step introspects your configuration class so you could bind [configuration values](http://xvik.github.io/dropwizard-guicey/4.2.0/guide/bindings/#configuration-by-path) directly (or even  [sub-configuration objects](http://xvik.github.io/dropwizard-guicey/4.2.0/guide/bindings/#unique-sub-configuration)).

I was thinking about making this step optional but then assumed that configuration objects are pretty simple (usually)  and all cases should be already covered. I will look on your case (when will be able to reproduce) and will think one more time.

**Comment by krutsko** [comment]
It fails with simple `com.netflix.config.DynamicStringProperty` property insides my config.
For example:
```
package hello;

import com.netflix.config.DynamicStringProperty;
import io.dropwizard.Configuration;

public class TestConfig extends Configuration{
    public DynamicStringProperty getDynamicStringProperty() {
        return dynamicStringProperty;
    }

    private DynamicStringProperty dynamicStringProperty;
}
```

**Comment by xvik** [comment]
Oh, I forgot, there is a quick workaround for cases like this: you can use `@JsonIgnore` on getters of dynamic properties (or on getter of sub object, containing all such porperties).
Configuration introspection use jackson serialization and so will honor `@JsonIgnore` and will not introspect such objects.

More generally, I will catch such introspection errors and show warning instead of failing startup. Going to release the fixed version soon (few days).

**Comment by xvik** [comment]
version 4.2.1 [released](https://github.com/xvik/dropwizard-guicey/releases/tag/4.2.1)
[Disabling introspection doc](http://xvik.github.io/dropwizard-guicey/4.2.1/guide/bindings/#disable-configuration-introspection)
